#!/bin/bash

# Ensure all commands are run within this script's directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

# Add an exception for this directory, call:
git config --global --add safe.directory /workspaces/Auto-GPT/autogpts/evo.ninja

# Clone the repo and checkout the release branch
REPO="https://github.com/polywrap/evo.ninja"
BRANCH="release/autogpt"

echo "Cloning evo.ninja..."
git init
git remote add origin $REPO
git pull
git checkout $BRANCH

echo "Setup successfully."
